# Generated by Django 3.2 on 2023-05-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230501_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
