# Generated by Django 3.2 on 2023-05-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_subscribe',
            new_name='is_subscribed',
        ),
    ]
