# Generated by Django 3.2 on 2023-05-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_is_subscribe_user_is_subscribed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',), 'verbose_name': 'Имя пользователя', 'verbose_name_plural': 'Имена пользователей'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_subscribed',
        ),
    ]
